# This is a CI workflow for building and testing an Android application

name: CI

# Controls when the workflow will run
on:
  push:
    branches: [ "Mickein" ]
  pull_request:
    branches: [ "Mickein" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'  
          distribution: 'temurin' 

      - name: Create local.properties
        run: echo "sdk.dir=/opt/android-sdk" > local.properties

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Install Android SDK
        run: |
          mkdir -p /opt/android-sdk
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip -d /opt/android-sdk
          yes | sdkmanager --sdk_root=/opt/android-sdk --licenses
          sdkmanager --sdk_root=/opt/android-sdk "platform-tools" "platforms;android-33" "build-tools;33.0.0"

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run unit tests
        run: ./gradlew test

      - name: Run instrumentation tests
        run: ./gradlew connectedAndroidTest
